import uuid
from typing import Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Poster Agent API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory session store. Maps session_id -> list of prompts so the agent
# can later be wired up to use prior context for follow-up turns.
SESSIONS: dict[str, list[str]] = {}


class GenerateRequest(BaseModel):
    prompt: str
    session_id: Optional[str] = None
    use_memory: bool = False


class GenerateResponse(BaseModel):
    session_id: str
    html: str
    css: str
    used_memory: bool
    history_length: int


@app.get("/api/health")
def health():
    return {"status": "ok", "service": "poster-agent"}


def _mock_poster(prompt: str, used_memory: bool, turn: int) -> tuple[str, str]:
    """Return a mock (html, css) pair for the given prompt.

    The real agent will replace this with model output. The shape stays the
    same so the frontend contract does not change.
    """
    badge = "Follow-up" if used_memory else "New"
    accent = "#f97316" if used_memory else "#6366f1"
    safe_prompt = prompt.strip() or "Untitled poster"

    html = f"""
<div class="poster">
  <div class="poster__badge">{badge} · v{turn}</div>
  <h1 class="poster__title">{safe_prompt}</h1>
  <p class="poster__tag">An AI-generated concept poster</p>
  <div class="poster__grid">
    <div class="poster__cell poster__cell--a">DESIGN</div>
    <div class="poster__cell poster__cell--b">AI</div>
    <div class="poster__cell poster__cell--c">2026</div>
    <div class="poster__cell poster__cell--d">★</div>
  </div>
  <div class="poster__footer">generated by poster-agent</div>
</div>
""".strip()

    css = f"""
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; height: 100%; font-family: 'Inter', system-ui, sans-serif; }}
body {{
  background: radial-gradient(circle at 20% 0%, {accent}33, transparent 60%), #0b1020;
  display: flex; align-items: center; justify-content: center; padding: 24px;
}}
.poster {{
  width: 100%; max-width: 480px; aspect-ratio: 3/4;
  background: linear-gradient(160deg, #111827 0%, #1f2937 100%);
  border-radius: 24px; padding: 32px; color: #f9fafb;
  display: flex; flex-direction: column; gap: 18px;
  border: 1px solid rgba(255,255,255,0.08);
  box-shadow: 0 30px 60px rgba(0,0,0,0.45);
}}
.poster__badge {{
  align-self: flex-start; font-size: 12px; letter-spacing: 0.18em;
  text-transform: uppercase; padding: 6px 10px; border-radius: 999px;
  background: {accent}; color: #0b1020; font-weight: 700;
}}
.poster__title {{ font-size: 38px; line-height: 1.05; margin: 0; font-weight: 800; }}
.poster__tag {{ margin: 0; color: #9ca3af; font-size: 14px; }}
.poster__grid {{
  margin-top: auto; display: grid;
  grid-template-columns: 1fr 1fr; gap: 10px;
}}
.poster__cell {{
  border-radius: 14px; padding: 18px;
  font-weight: 700; letter-spacing: 0.08em; font-size: 13px;
  display: flex; align-items: flex-end; min-height: 90px;
}}
.poster__cell--a {{ background: {accent}; color: #0b1020; }}
.poster__cell--b {{ background: #f9fafb; color: #0b1020; }}
.poster__cell--c {{ background: #1e293b; color: #f9fafb; }}
.poster__cell--d {{ background: #0b1020; color: {accent}; border: 1px solid {accent}; font-size: 28px; }}
.poster__footer {{ font-size: 11px; color: #6b7280; letter-spacing: 0.2em; text-transform: uppercase; }}
""".strip()

    return html, css


@app.post("/api/generate", response_model=GenerateResponse)
def generate(req: GenerateRequest):
    if req.use_memory and req.session_id and req.session_id in SESSIONS:
        session_id = req.session_id
        SESSIONS[session_id].append(req.prompt)
        used_memory = True
    else:
        session_id = str(uuid.uuid4())
        SESSIONS[session_id] = [req.prompt]
        used_memory = False

    history = SESSIONS[session_id]
    html, css = _mock_poster(req.prompt, used_memory, len(history))

    return GenerateResponse(
        session_id=session_id,
        html=html,
        css=css,
        used_memory=used_memory,
        history_length=len(history),
    )


def main():
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)


if __name__ == "__main__":
    main()
